[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.setuptools",
  "python311Packages.pip", 
  "python311Packages.wheel"
]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install setuptools-scm"
]
