[phases.setup]
nixPkgs = [
  "python312",
  "python312Packages.setuptools",
  "python312Packages.pip",
  "python312Packages.wheel",
  "python312Packages.setuptools-scm"
]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install setuptools-scm"
]
